// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastlmm_mat
List fastlmm_mat(const arma::vec& Y, const arma::mat& X, const arma::mat& U, const arma::vec& s, const double& delta);
RcppExport SEXP _fastglmm_fastlmm_mat(SEXP YSEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(fastlmm_mat(Y, X, U, s, delta));
    return rcpp_result_gen;
END_RCPP
}
// fastlmm_spmat
List fastlmm_spmat(const arma::vec& Y, const arma::mat& X, const arma::sp_mat& U, const arma::vec& s, const double& delta);
RcppExport SEXP _fastglmm_fastlmm_spmat(SEXP YSEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(fastlmm_spmat(Y, X, U, s, delta));
    return rcpp_result_gen;
END_RCPP
}
// fastlmm_batch_mat
List fastlmm_batch_mat(const arma::mat& Y_all, const arma::mat& X, const arma::mat& U, const arma::vec& s, const double& delta);
RcppExport SEXP _fastglmm_fastlmm_batch_mat(SEXP Y_allSEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_all(Y_allSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(fastlmm_batch_mat(Y_all, X, U, s, delta));
    return rcpp_result_gen;
END_RCPP
}
// fastlmm_batch_spmat
List fastlmm_batch_spmat(const arma::mat& Y_all, const arma::mat& X, const arma::sp_mat& U, const arma::vec& s, const double& delta);
RcppExport SEXP _fastglmm_fastlmm_batch_spmat(SEXP Y_allSEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_all(Y_allSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(fastlmm_batch_spmat(Y_all, X, U, s, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastglmm_fastlmm_mat", (DL_FUNC) &_fastglmm_fastlmm_mat, 5},
    {"_fastglmm_fastlmm_spmat", (DL_FUNC) &_fastglmm_fastlmm_spmat, 5},
    {"_fastglmm_fastlmm_batch_mat", (DL_FUNC) &_fastglmm_fastlmm_batch_mat, 5},
    {"_fastglmm_fastlmm_batch_spmat", (DL_FUNC) &_fastglmm_fastlmm_batch_spmat, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastglmm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
