// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fastglmm.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastlmm_mm
List fastlmm_mm(const arma::vec& y, const arma::mat& X, const arma::mat& U, const arma::vec& s, const arma::vec& weights, const std::string& dcmpMethod, const double& delta, const double& left, const double& right, const double& tol, const double& lambda, const int& nthreads, const bool REML);
RcppExport SEXP _fastglmm_fastlmm_mm(SEXP ySEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP weightsSEXP, SEXP dcmpMethodSEXP, SEXP deltaSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP tolSEXP, SEXP lambdaSEXP, SEXP nthreadsSEXP, SEXP REMLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dcmpMethod(dcmpMethodSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type REML(REMLSEXP);
    rcpp_result_gen = Rcpp::wrap(fastlmm_mm(y, X, U, s, weights, dcmpMethod, delta, left, right, tol, lambda, nthreads, REML));
    return rcpp_result_gen;
END_RCPP
}
// fastlmm_ms
List fastlmm_ms(const arma::vec& y, const arma::mat& X, const arma::sp_mat& U, const arma::vec& s, const arma::vec& weights, const std::string& dcmpMethod, const double& delta, const double& left, const double& right, const double& tol, const double& lambda, const int& nthreads, const bool REML);
RcppExport SEXP _fastglmm_fastlmm_ms(SEXP ySEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP weightsSEXP, SEXP dcmpMethodSEXP, SEXP deltaSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP tolSEXP, SEXP lambdaSEXP, SEXP nthreadsSEXP, SEXP REMLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dcmpMethod(dcmpMethodSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type REML(REMLSEXP);
    rcpp_result_gen = Rcpp::wrap(fastlmm_ms(y, X, U, s, weights, dcmpMethod, delta, left, right, tol, lambda, nthreads, REML));
    return rcpp_result_gen;
END_RCPP
}
// fastlmm_sm
List fastlmm_sm(const arma::vec& y, const arma::sp_mat& X, const arma::mat& U, const arma::vec& s, const arma::vec& weights, const std::string& dcmpMethod, const double& delta, const double& left, const double& right, const double& tol, const double& lambda, const int& nthreads, const bool REML);
RcppExport SEXP _fastglmm_fastlmm_sm(SEXP ySEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP weightsSEXP, SEXP dcmpMethodSEXP, SEXP deltaSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP tolSEXP, SEXP lambdaSEXP, SEXP nthreadsSEXP, SEXP REMLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dcmpMethod(dcmpMethodSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type REML(REMLSEXP);
    rcpp_result_gen = Rcpp::wrap(fastlmm_sm(y, X, U, s, weights, dcmpMethod, delta, left, right, tol, lambda, nthreads, REML));
    return rcpp_result_gen;
END_RCPP
}
// fastlmm_ss
List fastlmm_ss(const arma::vec& y, const arma::sp_mat& X, const arma::sp_mat& U, const arma::vec& s, const arma::vec& weights, const std::string& dcmpMethod, const double& delta, const double& left, const double& right, const double& tol, const double& lambda, const int& nthreads, const bool REML);
RcppExport SEXP _fastglmm_fastlmm_ss(SEXP ySEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP weightsSEXP, SEXP dcmpMethodSEXP, SEXP deltaSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP tolSEXP, SEXP lambdaSEXP, SEXP nthreadsSEXP, SEXP REMLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dcmpMethod(dcmpMethodSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type REML(REMLSEXP);
    rcpp_result_gen = Rcpp::wrap(fastlmm_ss(y, X, U, s, weights, dcmpMethod, delta, left, right, tol, lambda, nthreads, REML));
    return rcpp_result_gen;
END_RCPP
}
// nb_theta
double nb_theta(const NumericVector& y, const NumericVector& mu, const double& n, const NumericVector& weights, const double& left, const double& right, const double& tol);
RcppExport SEXP _fastglmm_nb_theta(SEXP ySEXP, SEXP muSEXP, SEXP nSEXP, SEXP weightsSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const double& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(nb_theta(y, mu, n, weights, left, right, tol));
    return rcpp_result_gen;
END_RCPP
}
// fastglmm_mm
List fastglmm_mm(const arma::vec& y, const arma::mat& X, const arma::mat& U, const arma::vec& s, const arma::vec& weights, const arma::vec& offset, const std::string& family, const std::string& dcmpMethod, const double& delta, const double& left, const double& right, const double& tol, const double& tol_eta, const int& maxit, const double& lambda, const int& nthreads, const bool& doCoxReid);
RcppExport SEXP _fastglmm_fastglmm_mm(SEXP ySEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP weightsSEXP, SEXP offsetSEXP, SEXP familySEXP, SEXP dcmpMethodSEXP, SEXP deltaSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP tolSEXP, SEXP tol_etaSEXP, SEXP maxitSEXP, SEXP lambdaSEXP, SEXP nthreadsSEXP, SEXP doCoxReidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dcmpMethod(dcmpMethodSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol_eta(tol_etaSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type doCoxReid(doCoxReidSEXP);
    rcpp_result_gen = Rcpp::wrap(fastglmm_mm(y, X, U, s, weights, offset, family, dcmpMethod, delta, left, right, tol, tol_eta, maxit, lambda, nthreads, doCoxReid));
    return rcpp_result_gen;
END_RCPP
}
// fastglmm_ms
List fastglmm_ms(const arma::vec& y, const arma::mat& X, const arma::sp_mat& U, const arma::vec& s, const arma::vec& weights, const arma::vec& offset, const std::string& family, const std::string& dcmpMethod, const double& delta, const double& left, const double& right, const double& tol, const double& tol_eta, const int& maxit, const double& lambda, const int& nthreads, const bool& doCoxReid);
RcppExport SEXP _fastglmm_fastglmm_ms(SEXP ySEXP, SEXP XSEXP, SEXP USEXP, SEXP sSEXP, SEXP weightsSEXP, SEXP offsetSEXP, SEXP familySEXP, SEXP dcmpMethodSEXP, SEXP deltaSEXP, SEXP leftSEXP, SEXP rightSEXP, SEXP tolSEXP, SEXP tol_etaSEXP, SEXP maxitSEXP, SEXP lambdaSEXP, SEXP nthreadsSEXP, SEXP doCoxReidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dcmpMethod(dcmpMethodSEXP);
    Rcpp::traits::input_parameter< const double& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double& >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const double& >::type right(rightSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol_eta(tol_etaSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type doCoxReid(doCoxReidSEXP);
    rcpp_result_gen = Rcpp::wrap(fastglmm_ms(y, X, U, s, weights, offset, family, dcmpMethod, delta, left, right, tol, tol_eta, maxit, lambda, nthreads, doCoxReid));
    return rcpp_result_gen;
END_RCPP
}
// log_moments_nb_mu
DataFrame log_moments_nb_mu(const vec& mu, const double& theta, const string& method, const double& c, const double& p_tail);
RcppExport SEXP _fastglmm_log_moments_nb_mu(SEXP muSEXP, SEXP thetaSEXP, SEXP methodSEXP, SEXP cSEXP, SEXP p_tailSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const double& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_tail(p_tailSEXP);
    rcpp_result_gen = Rcpp::wrap(log_moments_nb_mu(mu, theta, method, c, p_tail));
    return rcpp_result_gen;
END_RCPP
}
// log_moments_nb_XB
DataFrame log_moments_nb_XB(const mat& X, const mat& Beta, const vec& offset, const vec& theta, const string& method, const double& c, const double& p_tail, const int& nthreads);
RcppExport SEXP _fastglmm_log_moments_nb_XB(SEXP XSEXP, SEXP BetaSEXP, SEXP offsetSEXP, SEXP thetaSEXP, SEXP methodSEXP, SEXP cSEXP, SEXP p_tailSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const mat& >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< const vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const double& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_tail(p_tailSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(log_moments_nb_XB(X, Beta, offset, theta, method, c, p_tail, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// log_moments_nb_BlupXBZ
DataFrame log_moments_nb_BlupXBZ(const mat& BLUP, const mat& X, const mat& Beta, const mat& Z, const vec& weights, const vec& offset, const vec& theta, const vec& delta, const string& method, const string& dcmpMethod, const double& c, const double& p_tail, const int& nthreads);
RcppExport SEXP _fastglmm_log_moments_nb_BlupXBZ(SEXP BLUPSEXP, SEXP XSEXP, SEXP BetaSEXP, SEXP ZSEXP, SEXP weightsSEXP, SEXP offsetSEXP, SEXP thetaSEXP, SEXP deltaSEXP, SEXP methodSEXP, SEXP dcmpMethodSEXP, SEXP cSEXP, SEXP p_tailSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const mat& >::type BLUP(BLUPSEXP);
    Rcpp::traits::input_parameter< const mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const mat& >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< const mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const string& >::type dcmpMethod(dcmpMethodSEXP);
    Rcpp::traits::input_parameter< const double& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_tail(p_tailSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(log_moments_nb_BlupXBZ(BLUP, X, Beta, Z, weights, offset, theta, delta, method, dcmpMethod, c, p_tail, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// log_moments_nb_BlupXBZ_sp
DataFrame log_moments_nb_BlupXBZ_sp(const mat& BLUP, const mat& X, const mat& Beta, const sp_mat& Z, const vec& weights, const vec& offset, const vec& theta, const vec& delta, const string& method, const string& dcmpMethod, const double& c, const double& p_tail, const int& nthreads);
RcppExport SEXP _fastglmm_log_moments_nb_BlupXBZ_sp(SEXP BLUPSEXP, SEXP XSEXP, SEXP BetaSEXP, SEXP ZSEXP, SEXP weightsSEXP, SEXP offsetSEXP, SEXP thetaSEXP, SEXP deltaSEXP, SEXP methodSEXP, SEXP dcmpMethodSEXP, SEXP cSEXP, SEXP p_tailSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const mat& >::type BLUP(BLUPSEXP);
    Rcpp::traits::input_parameter< const mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const mat& >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< const sp_mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const string& >::type dcmpMethod(dcmpMethodSEXP);
    Rcpp::traits::input_parameter< const double& >::type c(cSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_tail(p_tailSEXP);
    Rcpp::traits::input_parameter< const int& >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(log_moments_nb_BlupXBZ_sp(BLUP, X, Beta, Z, weights, offset, theta, delta, method, dcmpMethod, c, p_tail, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastglmm_fastlmm_mm", (DL_FUNC) &_fastglmm_fastlmm_mm, 13},
    {"_fastglmm_fastlmm_ms", (DL_FUNC) &_fastglmm_fastlmm_ms, 13},
    {"_fastglmm_fastlmm_sm", (DL_FUNC) &_fastglmm_fastlmm_sm, 13},
    {"_fastglmm_fastlmm_ss", (DL_FUNC) &_fastglmm_fastlmm_ss, 13},
    {"_fastglmm_nb_theta", (DL_FUNC) &_fastglmm_nb_theta, 7},
    {"_fastglmm_fastglmm_mm", (DL_FUNC) &_fastglmm_fastglmm_mm, 17},
    {"_fastglmm_fastglmm_ms", (DL_FUNC) &_fastglmm_fastglmm_ms, 17},
    {"_fastglmm_log_moments_nb_mu", (DL_FUNC) &_fastglmm_log_moments_nb_mu, 5},
    {"_fastglmm_log_moments_nb_XB", (DL_FUNC) &_fastglmm_log_moments_nb_XB, 8},
    {"_fastglmm_log_moments_nb_BlupXBZ", (DL_FUNC) &_fastglmm_log_moments_nb_BlupXBZ, 13},
    {"_fastglmm_log_moments_nb_BlupXBZ_sp", (DL_FUNC) &_fastglmm_log_moments_nb_BlupXBZ_sp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastglmm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
