# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fastlmm_mm <- function(y, X, U, s, weights, dcmpMethod, delta, left, right, tol, nthreads, REML = FALSE) {
    .Call('_fastglmm_fastlmm_mm', PACKAGE = 'fastglmm', y, X, U, s, weights, dcmpMethod, delta, left, right, tol, nthreads, REML)
}

.fastlmm_ms <- function(y, X, U, s, weights, dcmpMethod, delta, left, right, tol, nthreads, REML = FALSE) {
    .Call('_fastglmm_fastlmm_ms', PACKAGE = 'fastglmm', y, X, U, s, weights, dcmpMethod, delta, left, right, tol, nthreads, REML)
}

.fastlmm_sm <- function(y, X, U, s, weights, dcmpMethod, delta, left, right, tol, nthreads, REML = FALSE) {
    .Call('_fastglmm_fastlmm_sm', PACKAGE = 'fastglmm', y, X, U, s, weights, dcmpMethod, delta, left, right, tol, nthreads, REML)
}

.fastlmm_ss <- function(y, X, U, s, weights, dcmpMethod, delta, left, right, tol, nthreads, REML = FALSE) {
    .Call('_fastglmm_fastlmm_ss', PACKAGE = 'fastglmm', y, X, U, s, weights, dcmpMethod, delta, left, right, tol, nthreads, REML)
}

.nb_theta <- function(y, mu, n, weights, left = -5, right = 20, tol = 1e-5) {
    .Call('_fastglmm_nb_theta', PACKAGE = 'fastglmm', y, mu, n, weights, left, right, tol)
}

.fastglmm_mm <- function(y, X, U, s, weights, offset, family, dcmpMethod, delta, left, right, tol, tol_eta, maxit, nthreads) {
    .Call('_fastglmm_fastglmm_mm', PACKAGE = 'fastglmm', y, X, U, s, weights, offset, family, dcmpMethod, delta, left, right, tol, tol_eta, maxit, nthreads)
}

.fastglmm_ms <- function(y, X, U, s, weights, offset, family, dcmpMethod, delta, left, right, tol, tol_eta, maxit, nthreads) {
    .Call('_fastglmm_fastglmm_ms', PACKAGE = 'fastglmm', y, X, U, s, weights, offset, family, dcmpMethod, delta, left, right, tol, tol_eta, maxit, nthreads)
}

