# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fastlmm_c <- function(Y, X, U, s, delta) {
    .Call('_fastglmm_fastlmm_c', PACKAGE = 'fastglmm', Y, X, U, s, delta)
}

.fastlmm_batch_c <- function(Y_all, X, U, s, delta) {
    .Call('_fastglmm_fastlmm_batch_c', PACKAGE = 'fastglmm', Y_all, X, U, s, delta)
}

