# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Rebuild TMB from source on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          Rscript -e '
            lib <- .libPaths()[1]

            if ("TMB" %in% rownames(installed.packages(lib.loc = lib))) {
              remove.packages("TMB", lib = lib)
            }

            # install from binary
            # since its _much_ faster
            install.packages(
              c("lme4", "numDeriv", "reformulas", "pbkrtest", "sandwich", "RcppEigen"),
              repos = "https://cloud.r-project.org",
              type = "binary",
              dependencies = TRUE,
              lib = lib)

            # install from source
            # since TMB binary was combined with OpenMP
            # but testing machine doesn't have OpenMP
            install.packages(
              c("TMB", "glmmTMB"),
              type = "source",
              repos = "https://cloud.r-project.org",
              dependencies = FALSE,
              lib = lib
            )'

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
